export const obras = [
  {
    id:1,
    titulo:"Bien común",
    tecnica:"Tiralíneas 0.9 mm sobre papel algodon 40 gr. montaje digital ",
    year:"2019 /11 copias 2022",
    autor:"Loreto Carrasco",
    formato:"Impreso por primera vez en 2020 por revista “Brigidas”N*7. Reimpreso sobre papel hilado 200 gr 29,7 x 42 cm. en venta. 5 copias disponibles",
    image:"../../images/dibujos/1.webp",
  },
  {
    id:2,
    titulo:"Danza de marco",
    tecnica:"Retrato de memoria en policromo celeste sobre fabriano hueso 90 gr	",
    year:"2021",
    autor:"Loreto Carrasco",
    formato:"22,9 x 30,3 cm Marco mañio 1,3 x 2 cm cubierta de vidrio, en venta",
    image:"../../images/dibujos/2.webp",
  },
  {
    id:3,
    titulo:"Descanso",
    tecnica:"Policromo naranjo y grafitos 2h al 8b sobre papel 120 gr algodon",
    year:"2018",
    autor:"Loreto Carrasco",
    formato:"21 x 21 cm para enmarcar, en venta",
    image:"../../images/dibujos/3.webp",
  },
  {
    id:4,
    titulo:"Coordinación austral",
    tecnica:"Tiralineas 0.2 azul y naranjo sobre hilado blanco 90 g	",
    year:"2021",
    autor:"Cristina Daza	",
    formato:"23 x 31,3 cm Marco aluminio redondeado 0,7 x 2 cm cubierta de vidrio",
    image:"../../images/dibujos/4.webp",
  },
  {
    id:5,
    titulo:"El mundo",
    tecnica:"Tiralíneas 0.4 sobre papel 160 g, libre de ácido",
    year:"2020",
    autor:"Cristina Daza	",
    formato:"25,5 x 31,2 cm Marco mañio 1,3 x 1,3 cm cubierta de vidrio, en venta",
    image:"../../images/dibujos/5.webp",
  },
  {
    id:6,
    titulo:"Sonic",
    tecnica:"Tiralíneas negro 0.2 mm sobre papel 160 g libre de acido",
    year:"2020",
    autor:"Cristina Daza	",
    formato:"20,2 x 25,3 cm Marco mañio 1,3 x 1,3 cm cubierta de vidrio",
    image:"../../images/dibujos/6.webp",
  },
  {
    id:7,
    titulo:"Impacto",
    tecnica:"Oleo rojo, policromos; morado, verde, cian, magenta, grafito del 2h al 8b",
    year:"2021",
    autor:"Loreto Carrasco",
    formato:"158,8 x 114,8 Marco madera pintada en acrilico rojo 3 x 1,3 cm cubierta de vididrio, en venta",
    image:"../../images/dibujos/7.webp",
  },
  {
    id:8,
    titulo:"Eleonore Elizabeth",
    tecnica:"Retrato instrospectivo, lápiz policromo celeste, grafito del 2h al 8b sobre papel fabriano 250 gr 50% algodon",
    year:"2019",
    autor:"Loreto Carrasco",
    formato:"32,5 x 41,2 cm Marco aluminio brillo cálido 1 x 2 cm cubierta vidrio, Se realizan a pedido con audio de voz nombrando al retratadx.",
    image:"../../images/dibujos/8.webp",
  },
  {
    id:9,
    titulo:"Loretta Pascal",
    tecnica:"Retrato instrospectivo, lápiz policromo celeste, grafito del 2h al 8b sobre papel fabriano 250 gr 50% algodon",
    year:"2018",
    autor:"Loreto Carrasco",
    formato:"32,5 x 41,2 cm Marco aluminio brillo cálido 1 x 2 cm cubierta vidrio. Se realizan a pedido con audio de voz nombrando al retratadx",
    image:"../../images/dibujos/9.webp",
  },
  {
    id:10,
    titulo:"Roiffrancia",
    tecnica:"Intervención fílmica en formato 35 mm con acrílico. Digitalizado e impreso en papel fine art",
    year:"2019",
    autor:"Cristina Daza",
    formato:"Intervención fílmica en formato 35 mm con acrílico. Digitalizado e impreso en papel fine art",
    image:"../../images/dibujos/10.webp",
  },
  {
    id:11,
    titulo:"Roif hongo",
    tecnica:"Intervención fílmica en formato 35 mm con hongos de fruta y raspados con bisturí. Digitalizado e impreso en papel fine art	",
    year:"2019",
    autor:"Cristina Daza",
    formato:"Intervención fílmica en formato 35 mm con hongos de fruta y raspados con bisturí. Digitalizado e impreso en papel fine art",
    image:"../../images/dibujos/11.webp",
  },
  {
    id:12,
    titulo:"Tierra blanda",
    tecnica:"Fotografia analoga 35 mm digitalizada",
    year:"2021",
    autor:"Cristina Daza",
    formato:"Fotografia analoga 35 mm digitalizada ",
    image:"../../images/dibujos/12.webp",
  },
  {
    id:13,
    titulo:"4to Nectar",
    tecnica:"Pincel tinta negra y policromos azul, naranjo y verde sobre canson hueso 90 gr",
    year:"2022",
    autor:"Loreto Carrasco",
    formato:"14,8 x 21 cm sketch, en venta",
    image:"../../images/dibujos/13.webp",
  },
  {
    id:14,
    titulo:"Kiki",
    tecnica:"Policromo celeste  grafitos 2h al 8b sobre papel 120 gr algodon",
    year:"2018",
    autor:"Loreto Carrasco",
    formato:"21 x 21 para enmarcar, en venta",
    image:"../../images/dibujos/14.webp",
  },
  {
    id:15,
    titulo:"Nina sobre Nina",
    tecnica:"Policromo rosado  grafitos 2h al 8b sobre papel 120 gr algodon",
    year:"2018",
    autor:"Loreto Carrasco",
    formato:"21 x 21 para enmarcar, en venta",
    image:"../../images/dibujos/15.webp",
  },
  {
    id:16,
    titulo:"Manipulación prevista",
    tecnica:"Pincel tinta negra y policromos naranjo y verde sobre canson hueso 90 gr",
    year:"2022",
    autor:"Loreto Carrasco",
    formato:"14,8 x 21 cm sketch, en venta",
    image:"../../images/dibujos/16.webp",
  },
  {
    id:17,
    titulo:"Cuerpo",
    tecnica:"Pincel tinta negra y policromos naranjo  sobre canson hueso 90 gr",
    year:"2022",
    autor:"Loreto Carrasco",
    formato:"14,8 x 21 cm sketch, en venta",
    image:"../../images/dibujos/17.webp",
  },
  {
    id:18,
    titulo:"Condensacion del fuego",
    tecnica:"Policromo naranjo sobre canson hueso 90 gr",
    year:"2022",
    autor:"Loreto Carrasco",
    formato:"14,8 x 21 cm sketch, en venta",
    image:"../../images/dibujos/18.webp",
  },
]